### ISSUE TITLE
Buffer.from(...).swap64 is not a function

### ISSUE THREAD

**Issue by samjhill** [mably/lncli-web#103]
Thanks for putting this together!

After adding the newly-generated lnd.cert file per instructions, I get the following error:

```shell
lncli-web sahill59$ node server --lndhost=localhost:10001
{ pubKeyHex: '0315976de23b04f363f6b3a23cb7263c1fe98b5de18e4210fb67c52c810df1b04b',
  paymentHashHex: '4e67764598fca6b07f96e706b9e3c3561fbd2f38cc019f97e4c503123b5bfe77',
  value: 3 }
/Users/sahill59/Documents/opensource/lncli-web/app/zpay32.js:86
	return Buffer.from(byteArray).swap64();
	                              ^

TypeError: Buffer.from(...).swap64 is not a function
    at convertLongToBigEndianBuffer (/Users/sahill59/Documents/opensource/lncli-web/app/zpay32.js:86:32)
    at Object.module.encode (/Users/sahill59/Documents/opensource/lncli-web/app/zpay32.js:20:24)
    at Object.<anonymous> (/Users/sahill59/Documents/opensource/lncli-web/app/zpay32.js:110:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

How can I fix this? Thanks in advance.

**Comment by samjhill** [comment]
Upgrading my Node version fixed this. 

https://stackoverflow.com/a/12570971
