### ISSUE TITLE
Cannot open admin.macaroon

### ISSUE THREAD

**Issue by RHavar** [mably/lncli-web#116]
I'm running lnd with --no-macaroons  and launching this project with `node server` results in a crash on boot:

```
Error: ENOENT: no such file or directory, open '/Users/rwilson/workspace/lncli-web/config/../admin.macaroon'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at /Users/rwilson/workspace/lncli-web/app/lightning.js:19:29
    at /Users/rwilson/workspace/lncli-web/node_modules/grpc/src/credentials.js:121:5
```

So I created an empty file there, and it all launches fine =)

**Comment by mably** [comment]
Tried to handle the missing macaroon file a bit more gracefully.
