### ISSUE TITLE
Unable to connect to port 8280

### ISSUE THREAD

**Issue by xelawafs** [mably/lncli-web#123]
On running `node server` I get : `info:    App listening on localhost port 8280`

However, on navigating to `mydonamin:8280` the site can't be reached. My lnd is up and running

**Comment by mably** [comment]
Should work with localhost:8280

**Comment by domwoe** [comment]
I'm running lnd with neutrino and lncli-web on a headless raspberry pi. Should I be able to able to access http://[pi's IP on local network]:8280 ? Because that does not work at the moment. However I also get
`20808 ssl_transport_security.cc:979] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.`

**Comment by mably** [comment]
It should work.  May be you have some firewall rules forbidding access?

Check you have specified the server hostname using the `--serverhost` command line parameter.

You can list all the available cmd line parameters by running `node server --help`.

**Comment by domwoe** [comment]
Thx it "kind of" works. I can access the web server remotely. However, I'm getting these kinds of error messages and don't see anything on the UI

`debug:   ListPayments Error: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/pi/lncli-web/node_modules/grpc/src/client.js:64:15)
    at /home/pi/lncli-web/node_modules/grpc/src/client.js:583:15
debug:   ListPeers Error: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/pi/lncli-web/node_modules/grpc/src/client.js:64:15)
    at /home/pi/lncli-web/node_modules/grpc/src/client.js:583:15
debug:   ChannelBalance Error: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/pi/lncli-web/node_modules/grpc/src/client.js:64:15)
    at /home/pi/lncli-web/node_modules/grpc/src/client.js:583:15
debug:   WalletBalance Error: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/pi/lncli-web/node_modules/grpc/src/client.js:64:15)
    at /home/pi/lncli-web/node_modules/grpc/src/client.js:583:15
debug:   GetNetworkInfo Error: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/pi/lncli-web/node_modules/grpc/src/client.js:64:15)
    at /home/pi/lncli-web/node_modules/grpc/src/client.js:583:15
debug:   GetInfo Error: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/pi/lncli-web/node_modules/grpc/src/client.js:64:15)
    at /home/pi/lncli-web/node_modules/grpc/src/client.js:583:15
debug:   SubscribeInvoices Error Error: 14 UNAVAILABLE: Connect Failed
    at createStatusError (/home/pi/lncli-web/node_modules/grpc/src/client.js:64:15)
    at ClientReadableStream._emitStatusIfDone (/home/pi/lncli-web/node_modules/grpc/src/client.js:270:19)
    at ClientReadableStream._readsDone (/home/pi/lncli-web/node_modules/grpc/src/client.js:236:8)
    at readCallback (/home/pi/lncli-web/node_modules/grpc/src/client.js:296:12)
debug:   SubscribeInvoices Status code=14, details=Connect Failed,`

I'm running lnd without a btcd instance, but only with neutrino. Is this an issue?

**Comment by mably** [comment]
Looks like the server app can't connect to lnd via gRPC API.  Does `lncli` command line tool work fine?

Never tested `lncli-web` with neutrino on my side.

**Comment by xelawafs** [comment]
Adding the --serverhost flag worked for me with my domain. It would be great if this can be indicated on the installation docs for clarity with folks trying to access over the internet. I'll go ahead and do a pull request
