### ISSUE TITLE
Unable to run on Ubuntu 

### ISSUE THREAD

**Issue by resdat** [mably/lncli-web#130]
Trying to get this to run on linux (Ububtu) and getting the following error:

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.module.encode (/home/jrogers/lncli-web/app/zpay32.js:17:29)
    at Object.<anonymous> (/home/jrogers/lncli-web/app/zpay32.js:110:28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

When I compile, I get the following warnings:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.2

seems that fsevents if limited to osx, which may be causing this problem. Is the datatype "hex" not defined somewhere else where I can make this work on Ubuntu?

**Comment by capitalistdog** [comment]
`node --version` ?

Having issues of a different nature myself, trying to compare notes.
