### ISSUE TITLE
gulpfile.js has bug

### ISSUE THREAD

**Issue by jiyu3** [mably/lncli-web#183]
Hi 

I tried to install lncli-web, but I failed on `"./node_modules/.bin/gulp" bundle`.
```
[09:26:28] Using gulpfile ~/go/src/github.com/mably/lncli-web/gulpfile.js
[09:26:28] Task never defined: bundle
[09:26:28] To list available tasks, try running: gulp --tasks
```

I ran `gulp --tasks`, below returned:
```
[09:27:18] Using gulpfile ~/go/src/github.com/mably/lncli-web/gulpfile.js
/usr/local/lib/node_modules/gulp/lib/taskTree.js:4
  return Object.keys(tasks)
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/gulp/lib/taskTree.js:4:17)
    at logTasks (/usr/local/lib/node_modules/gulp/bin/gulp.js:134:14)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:127:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Something is wrong with `~/go/src/github.com/mably/lncli-web/gulpfile.js`.
Any idea?

**Comment by jiyu3** [comment]
It works.
