### ISSUE TITLE
NPM Install --  Fails 

### ISSUE THREAD

**Issue by Luke-JCSC** [mably/lncli-web#185]
- on linux mint 18  --  Tried numerous things it keeps failing.  

32651 silly saveTree │ └── eyes@0.1.8
32651 silly saveTree └── zbase32@0.0.2
32652 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
32653 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
32654 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
32654 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
32654 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
32654 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
32655 warn optional SKIPPING OPTIONAL DEPENDENCY: sse4_crc32@5.2.0 (node_modules/sse4_crc32):
32656 warn optional SKIPPING OPTIONAL DEPENDENCY: sse4_crc32@5.2.0 install: `node-gyp rebuild`
32656 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
32657 verbose optional SKIPPING OPTIONAL DEPENDENCY:
32657 verbose optional Failed at the sse4_crc32@5.2.0 install script.
32657 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
32658 warn optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules/ursa):
32659 warn optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
32659 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
32660 verbose optional SKIPPING OPTIONAL DEPENDENCY:
32660 verbose optional Failed at the ursa@0.9.4 install script.
32660 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
32661 verbose stack Error: grpc@1.13.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
32661 verbose stack Exit status 1
32661 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
32661 verbose stack     at EventEmitter.emit (events.js:197:13)
32661 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
32661 verbose stack     at ChildProcess.emit (events.js:197:13)
32661 verbose stack     at maybeClose (internal/child_process.js:978:16)
32661 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
32662 verbose pkgid grpc@1.13.0
32663 verbose cwd /home/gabe/gocode/src/github.com/lightningnetwork/lncli-web
32664 verbose Linux 4.4.0-142-generic
32665 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
32666 verbose node v11.9.0
32667 verbose npm  v6.5.0
32668 error code ELIFECYCLE
32669 error errno 1
32670 error grpc@1.13.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
32670 error Exit status 1
32671 error Failed at the grpc@1.13.0 install script.
32671 error This is probably not a problem with npm. There is likely additional logging output above.
32672 verbose exit [ 1, true ]

**Comment by Luke-JCSC** [comment]
[2019-02-12T02_58_48_615Z-debug.log](https://github.com/mably/lncli-web/files/2853972/2019-02-12T02_58_48_615Z-debug.log)
[2019-02-11T01_56_43_038Z-debug.log](https://github.com/mably/lncli-web/files/2853974/2019-02-11T01_56_43_038Z-debug.log)


Any help would be appreciated.

**Comment by enorrmann** [comment]
try by updating packages.json
   "grpc": "^1.13.0",
to
    "grpc": "^1.18.0",
.. this lib seems a bit outdated @mably ?

**Comment by mably** [comment]
Have you tested that grpc version?  I can update it if it works fine.  Will give it a try when I have some time.

**Comment by enorrmann** [comment]
My envirinment is as follows
Ubuntu 18.10
node -v 
v8.15.0 (from nodejs.org)
uname -a
Linux 4.18.0-15-generic x86_64 

these are the steps I followed to get it working 

1. git clone https://github.com/mably/lncli-web.git
2. cd lncli-web
3. **npm install grpc**
4. **npm install electron**
5. npm install 
6. init.sh

steps 3 and 4 updated the to grpc 1.8 and electron 1.8.8.. and that did the trick for me

**Comment by mably** [comment]
Updated package.json to grpc 1.18.0
