### ISSUE TITLE
start server bug

### ISSUE THREAD

**Issue by ctow123** [mably/lncli-web#234]
really disappointed, this a part of a popular tutorial and spending 2 hours just trying to build this. very disappointing

/Users/connormbp/go/src/github.com/mably/lncli-web/node_modules/winston/lib/winston/common.js:26
      throw new Error([
      ^

Error: { cli } was removed in winston@3.0.0.
Use a custom winston.format = winston.format(function) instead.
    at Object.cli (/Users/connormbp/go/src/github.com/mably/lncli-web/node_modules/winston/lib/winston/common.js:26:13)
    at factory (/Users/connormbp/go/src/github.com/mably/lncli-web/config/log.js:7:11)
    at factory (/Users/connormbp/go/src/github.com/mably/lncli-web/app/server.js:26:42)
    at Object.<anonymous> (/Users/connormbp/go/src/github.com/mably/lncli-web/server.js:29:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by mably** [comment]
I sadly don't have time to maintain this project anymore.

I accidentally merged a few security updates which seem to be incompatible with current codebase.

Try going back a few commits. 

It would be even better if you could suggest a fix to the problem.  MRs welcomed.
