### ISSUE TITLE
Can't find lnd.cert

### ISSUE THREAD

**Issue by grant-olson** [mably/lncli-web#93]
Hello,
Found this project via dev.lightning.community tutorial. I try to fire up the app and I get this error:

```
Error: ENOENT: no such file or directory, open '/Users/grant/gocode/src/lncli-web/config/../lnd.cert'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at module.exports (/Users/grant/gocode/src/lncli-web/app/lightning.js:12:19)
    at module.exports (/Users/grant/gocode/src/lncli-web/app/server.js:38:42)
    at Object.<anonymous> (/Users/grant/gocode/src/lncli-web/server.js:27:25)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

My initial guess is this has to do with TLS or some of the certificates mentioned in the README, but none of them are named lnd.cert.

**Comment by mably** [comment]
Hi, thanks for using the lnd web client.  The `lnd.cert` file is generated by the `lnd` daemon.  You should probably find it in the `.lnd` directory or in the corresponding `AppData` folder on Windows.  You need to start `lnd` at least once to generate the `lnd.cert` file.

**Comment by Haafingar** [comment]
I am having the same issue. Both me and my colleague are trying to get this client up. LND is running on the desired ports, but no such file exists in any directory on the machine. At a loss to figure out what to do next, there is very little in the way of documentation regarding the cert file.

`fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\LND\lncli-web\lncli-web\lnd.cert'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at module.exports (C:\LND\lncli-web\lncli-web\app\lightning.js:12:19)
    at module.exports (C:\LND\lncli-web\lncli-web\app\server.js:38:42)
    at Object.<anonymous> (C:\LND\lncli-web\lncli-web\server.js:27:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
`

**Comment by Ematupo** [comment]
I have the same problem. Does anyone have the solution now?

**Comment by mably** [comment]
You probably need to generate the lnd.cert file using the instructions available here:

https://github.com/mably/lncli-web/blob/master/README.md#generate-lnd-certificates-compatible-with-nodejs-grpc

**Comment by mably** [comment]
@ianrussel you must start `lnd` once for the `.lnd` directory to be created.

**Comment by ianrussel** [comment]
@mably  yeah already fixed the issue by manually installing lnd
